sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubctl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project k8s-gcp-282121
  - gcloud config set compute/zone us-west1-a
  - gcloud container clusters get-credentials mult-cluster
script:
  - docker run -e CI=true USENAME/docker-react npm run test

